sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql
    port: 3306
    database: sky_take_out
    username: root
    password: ${MYSQL_PASSWORD:sky123456}
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIOSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET}
    bucket-name: ${ALIOSS_BUCKET_NAME:sky-take-out-xf1}
  redis:
    host: redis
    port: 6379
    database: 10
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
