sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tDnQnatwJWST5dkLY3d
    access-key-secret: mwsMqpYEtR5SpvW5RyOKPqM1G0zxQC
    bucket-name: sky-take-out-xf1
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx99c4a6db8370756c
    secret: a1c96cad9621055c7193bb31cc9593cb